# Generated by Django 5.2.4 on 2025-07-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_flight_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_names',
            old_name='name',
            new_name='flight_name',
        ),
    ]
