# Generated by Django 5.2.4 on 2025-07-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_history_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passenger_details',
        ),
    ]
