# Generated by Django 5.2.4 on 2025-07-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_passenger_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='passenger_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('from_departure', models.CharField(max_length=100)),
                ('to_destination', models.CharField(max_length=100)),
            ],
        ),
    ]
