# Generated by Django 5.2.4 on 2025-07-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_passenger_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='history_model',
        ),
    ]
