# Generated by Django 5.2.4 on 2025-07-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_history_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flight_details',
        ),
    ]
