# Generated by Django 5.2.4 on 2025-07-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_flight_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=100)),
                ('destination_time', models.CharField(max_length=100)),
                ('seat_availibility', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='flight_names',
        ),
    ]
