# Generated by Django 5.2.4 on 2025-07-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_flight_details_delete_flight_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight_company_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=100)),
            ],
        ),
    ]
