# Generated by Django 5.2.4 on 2025-07-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_flight_company_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flight_details',
        ),
        migrations.DeleteModel(
            name='history_model',
        ),
        migrations.DeleteModel(
            name='passenger_details',
        ),
    ]
