# Generated by Django 5.2.4 on 2025-07-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_flight_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flight_details',
        ),
    ]
