# Generated by Django 5.2.4 on 2025-07-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_flight_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=100)),
                ('flight_name', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=100)),
                ('destination_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='passenger_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=100)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_departure', to='base.flight_details')),
                ('departure_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_departure_time', to='base.flight_details')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_destination', to='base.flight_details')),
                ('destination_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_destination_time', to='base.flight_details')),
                ('flight_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_flight_name', to='base.flight_details')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_price', to='base.flight_details')),
            ],
        ),
    ]
