# Generated by Django 5.2.4 on 2025-07-06 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_history_model_passenger_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='history_model',
        ),
        migrations.RemoveField(
            model_name='passenger_details',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='passenger_details',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='passenger_details',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='passenger_details',
            name='destination_time',
        ),
        migrations.RemoveField(
            model_name='passenger_details',
            name='flight_name',
        ),
        migrations.RemoveField(
            model_name='passenger_details',
            name='price',
        ),
        migrations.AddField(
            model_name='passenger_details',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flight_details'),
        ),
    ]
