# Generated by Django 5.2.4 on 2025-07-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_delete_history_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passenger_details',
        ),
    ]
