# Generated by Django 5.2.4 on 2025-07-07 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_delete_passenger_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='passenger_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=100)),
                ('destination_time', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=100)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flight_details')),
            ],
        ),
    ]
