# Generated by Django 5.2.4 on 2025-07-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_passenger_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=100)),
                ('flight_name', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=100)),
                ('destination_time', models.CharField(max_length=100)),
            ],
        ),
    ]
