# Generated by Django 5.2.4 on 2025-07-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_history_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_departure', models.CharField(max_length=100)),
                ('flight_destination', models.CharField(max_length=100)),
                ('flight_departure_time', models.CharField(max_length=100)),
                ('flight_destination_time', models.CharField(max_length=100)),
                ('flight_ticket_price', models.CharField(max_length=100)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.CharField(max_length=100)),
                ('passenger_gender', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=100)),
                ('passenger_email', models.CharField(max_length=100)),
                ('passenger_aadhar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='historyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_departure', models.CharField(max_length=100)),
                ('flight_destination', models.CharField(max_length=100)),
                ('flight_departure_time', models.CharField(max_length=100)),
                ('flight_destination_time', models.CharField(max_length=100)),
                ('flight_ticket_price', models.CharField(max_length=100)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.CharField(max_length=100)),
                ('passenger_gender', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=100)),
                ('passenger_email', models.CharField(max_length=100)),
                ('passenger_aadhar', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='flight_company_model',
            new_name='flight_companies',
        ),
        migrations.DeleteModel(
            name='history_model',
        ),
        migrations.RenameField(
            model_name='flight_companies',
            old_name='flight_company',
            new_name='flight_company_name',
        ),
        migrations.RenameField(
            model_name='flight_details',
            old_name='departure',
            new_name='flight_company_name',
        ),
        migrations.RenameField(
            model_name='flight_details',
            old_name='departure_time',
            new_name='flight_departure',
        ),
        migrations.RenameField(
            model_name='flight_details',
            old_name='destination',
            new_name='flight_departure_time',
        ),
        migrations.RenameField(
            model_name='flight_details',
            old_name='destination_time',
            new_name='flight_destination',
        ),
        migrations.RenameField(
            model_name='flight_details',
            old_name='price',
            new_name='flight_destination_time',
        ),
        migrations.RenameField(
            model_name='flight_details',
            old_name='seat_availibility',
            new_name='flight_ticket_price',
        ),
        migrations.RemoveField(
            model_name='flight_details',
            name='flight_company',
        ),
        migrations.DeleteModel(
            name='passenger_details',
        ),
    ]
